<a href="https://colab.research.google.com/github/AlexitoFernandez/practicas-google-colab/blob/practica-1/Clase_d%C3%ADa_11_02_2026-DataWrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# "Machine Learning"
## Unidad I - Introducción a Machine Learning
### **Practica 1 - Datawrangling**
Alumno: Jorge Alejandro Fernández De Los Santos.

Facilitador: José Gabriel Rodríguez Rivas.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from google.colab import drive

print("Libraries loaded successfully.")
drive.mount('/content/drive')

Libraries loaded successfully.
Mounted at /content/drive

In [ ]:
!pip install gdown --quiet
!gdown --id 1Za0TQvQIdIPIwsp9T3c6vz0i-B6XzqHY -O iowa_liquor_sales_data.csv

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1Za0TQvQIdIPIwsp9T3c6vz0i-B6XzqHY
To: /content/iowa_liquor_sales_data.csv
100% 25.1k/25.1k [00:00<00:00, 55.0MB/s]

In [ ]:
df_sales = pd.read_csv('iowa_liquor_sales_data.csv')
print(df_sales.head(10))

   symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two
1          3                 ?  alfa-romero       gas        std          two
2          1                 ?  alfa-romero       gas        std          two
3          2               164         audi       gas        std         four
4          2               164         audi       gas        std         four
5          2                 ?         audi       gas        std          two
6          1               158         audi       gas        std         four
7          1                 ?         audi       gas        std         four
8          1               158         audi       gas      turbo         four
9          0                 ?         audi       gas      turbo          two

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130
1  convertible          rwd           front        88.6  ...          130
2    hatchback          rwd           front        94.5  ...          152
3        sedan          fwd           front        99.8  ...          109
4        sedan          4wd           front        99.4  ...          136
5        sedan          fwd           front        99.8  ...          136
6        sedan          fwd           front       105.8  ...          136
7        wagon          fwd           front       105.8  ...          136
8        sedan          fwd           front       105.8  ...          131
9    hatchback          4wd           front        99.5  ...          131

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21
1         mpfi  3.47    2.68               9.0        111      5000       21
2         mpfi  2.68    3.47               9.0        154      5000       19
3         mpfi  3.19     3.4              10.0        102      5500       24
4         mpfi  3.19     3.4               8.0        115      5500       18
5         mpfi  3.19     3.4               8.5        110      5500       19
6         mpfi  3.19     3.4               8.5        110      5500       19
7         mpfi  3.19     3.4               8.5        110      5500       19
8         mpfi  3.13     3.4               8.3        140      5500       17
9         mpfi  3.13     3.4               7.0        160      5500       16

  highway-mpg  price
0          27  13495
1          27  16500
2          26  16500
3          30  13950
4          22  17450
5          25  15250
6          25  17710
7          25  18920
8          20  23875
9          22      ?

[10 rows x 26 columns]

In [ ]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [ ]:
df_sales.head(10) #Se muestran las primeras 10 columnas

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?

In [ ]:
df_sales.replace("?",np.nan,inplace=True)  #Se va a reemplazar el "?" por un "NaN (Not a Number)"
df_sales.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,NaN

In [ ]:
df_sales.isna().sum().sort_values() #Contar valores perdidos en todas las columnas

symboling             0
make                  0
fuel-type             0
aspiration            0
drive-wheels          0
body-style            0
wheel-base            0
engine-location       0
height                0
curb-weight           0
length                0
width                 0
engine-type           0
num-of-cylinders      0
fuel-system           0
engine-size           0
highway-mpg           0
compression-ratio     0
city-mpg              0
num-of-doors          2
peak-rpm              2
horsepower            2
bore                  4
stroke                4
price                 4
normalized-losses    41
dtype: int64

In [ ]:
avg_norm_loss = df_sales["normalized-losses"].astype("float").mean(axis=0)
print("Promedio de Normalized-losses: ", avg_norm_loss)

Promedio de Normalized-losses:  122.0

In [ ]:
df_sales["normalized-losses"].replace(np.nan, avg_norm_loss, inplace=False)

0      122.0
1      122.0
2      122.0
3        164
4        164
       ...
200       95
201       95
202       95
203       95
204       95
Name: normalized-losses, Length: 205, dtype: object

In [ ]:
avg_bore= df_sales["bore"].astype("float").mean(axis=0)
print("Promedio de bore: ", avg_bore)

Promedio de bore:  3.3297512437810943

In [ ]:
df_sales["bore"].replace(np.nan, avg_bore, inplace=False)

0      3.47
1      3.47
2      2.68
3      3.19
4      3.19
       ...
200    3.78
201    3.78
202    3.58
203    3.01
204    3.78
Name: bore, Length: 205, dtype: object

In [ ]:
avg_stroke= df_sales["stroke"].astype("float").mean(axis=0)
print("Promedio de stroke: ", avg_stroke)

Promedio de stroke:  3.255422885572139

In [ ]:
df_sales["stroke"].replace(np.nan, avg_stroke, inplace=False)

0      2.68
1      2.68
2      3.47
3       3.4
4       3.4
       ...
200    3.15
201    3.15
202    2.87
203     3.4
204    3.15
Name: stroke, Length: 205, dtype: object

In [ ]:
avg_hp= df_sales["horsepower"].astype("float").mean(axis=0)
print("Promedio de HorsePower: ", avg_hp)

Promedio de HorsePower:  104.25615763546799

In [ ]:
df_sales["horsepower"].replace(np.nan, avg_hp, inplace=False)

0      111
1      111
2      154
3      102
4      115
      ...
200    114
201    160
202    134
203    106
204    114
Name: horsepower, Length: 205, dtype: object

In [ ]:
avg_peakrpm= df_sales["peak-rpm"].astype("float").mean(axis=0)
print("Promedio de Peak RPM: ", avg_peakrpm)

Promedio de Peak RPM:  5125.369458128079

In [ ]:
df_sales["peak-rpm"].replace(np.nan, avg_peakrpm, inplace=False)

0      5000
1      5000
2      5000
3      5500
4      5500
       ...
200    5400
201    5300
202    5500
203    4800
204    5400
Name: peak-rpm, Length: 205, dtype: object

In [ ]:
df_sales["num-of-doors"].value_counts() #Número de puertas por cada valor

num-of-doors
four    114
two      89
Name: count, dtype: int64

In [ ]:
#Se reemplaza el número de puertas por el valor más frecuente.
df_sales["num-of-doors"].replace(np.nan, "four", inplace=False)

0       two
1       two
2       two
3      four
4      four
       ...
200    four
201    four
202    four
203    four
204    four
Name: num-of-doors, Length: 205, dtype: object

In [ ]:
#Se eliminan los valores faltantes en la columna de precios porque es lo que se pretende predecir
df_sales.dropna(subset=["price"], axis=0, inplace=True)

In [ ]:
#Se dan formato a los datos para mostrar valores numéricos
df_sales[["bore","stroke"]] = df_sales[["bore","stroke"]].astype("float")
df_sales[["normalised-losses"]] = df_sales[["normalized-losses"]].astype("int")
df_sales[["price"]] = df_sales[["price"]].astype("float")
df_sales[["peak-rpm"]] = df_sales[["peak-rpm"]].astype("float")
df_sales.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,normalised-losses
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,27,13495.0,122
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,27,16500.0,122
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000.0,19,26,16500.0,122
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500.0,24,30,13950.0,164
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500.0,18,22,17450.0,164
5,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,8.5,110,5500.0,19,25,15250.0,122
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,mpfi,3.19,3.40,8.5,110,5500.0,19,25,17710.0,158
7,1,122.0,audi,gas,std,four,wagon,fwd,front,105.8,...,mpfi,3.19,3.40,8.5,110,5500.0,19,25,18920.0,122
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,mpfi,3.13,3.40,8.3,140,5500.0,17,20,23875.0,158
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,mpfi,3.50,2.80,8.8,101,5800.0,23,29,16430.0,192